from pathlib import Path

DOCKER_FOLDER_NAME = "docker"

REPO_ROOT_DIR_PATH = Path(__file__).resolve().parent.parent

TEMPLATES_FOLDER_NAME = "templates"
TEMPLATES_DIR_PATH = REPO_ROOT_DIR_PATH / TEMPLATES_FOLDER_NAME

DAGS_FOLDER_TEMPLATE_STRING = "DAGS_FOLDER"
TESTS_FOLDER_TEMPLATE_STRING = "TESTS_FOLDER"
